### ISSUE TITLE
Running frontend & backend separately 

### ISSUE THREAD

**Issue by sah-anshu** [StreakyCobra/raposfly#55]
Can we run both services separately ? If yes, How do they communicate?

**Comment by StreakyCobra** [comment]
They do run separately. Frontend communicate with backend through HTTP requests: https://github.com/StreakyCobra/raposfly/blob/66e912bec2b225651893ca60de790cda60277bff/services/frontend/src/main.js#L40-L46

**Comment by sah-anshu** [comment]
Thanks.
